name: Hoang Win

on:
  workflow_dispatch:

jobs:
  build:
    name: khởi chạy...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Download
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: đăng nhập
        run: cmd /c show.bat

      - name: thời gian
        run: python time.py
