name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://uc38ec03cd20076cc6610f0903a2.dl.dropboxusercontent.com/cd/0/get/CKjNyjPmuSWiSTJn15gQHueCkqkvwOq1-XUZIGA24OtMB1NYMwqoVELWk2CMAy7ce2IpH2OZutx4PwKa2vm1lZHSUZ7mCuo43fBgm_AwRjHVHrbrkTJaFK_aqhfWPQ3P8rquSxEXsP8hlFyvN0AnVIvhF8RRH9UTf7mQO2pYxsTpjaTRdvrsQAT9vZVkuVm6HCE/file#" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py
